### ISSUE TITLE
Lua Error?

### ISSUE THREAD

**Issue by SkinnySatan** [Hoshikara/LucidWave#2]
The menus work perfectly but whenever I try to play a song I get an "Lua Error" that say "...Desktop\SDVX\skins/LucidWave-master/scripts/gameplay.lua:165: attempt to perform arithmetic on a nil value (field 'xOffset')". I'm not sure whether this is a bug or something on my end. Please help

**Comment by Hoshikara** [comment]
update your game by running updater.exe in your root USC folder

**Comment by SkinnySatan** [comment]
> update your game by running updater.exe in your root USC folder

I tried using the updater but I just got another error saying "The code execution cannot proceed because VCRUNTIME140_1.dll was not found."

**Comment by Hoshikara** [comment]
get the lastest visual c++ runtime

https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by SkinnySatan** [comment]
> get the lastest visual c++ runtime
> 
> https://aka.ms/vs/16/release/vc_redist.x64.exe

Woo it works now! Thank you very much! <3
