### ISSUE TITLE
some error.......

### ISSUE THREAD

**Issue by wz18207** [Hoshikara/LucidWave#7]
Hi,
    I may find the problem by using this skin on the windows:
    By 1st running, there are 2 file may not find in the files.
     1. /scripts/songselect/sortwheel.lua
     2. /scripts/gamesettingsdialog.lua
The system told me to copy from the default skin, shall i do it?
Also, as i do it. There has another bug by showing songs info:

![Snipaste_2020-07-14_12-55-05](https://user-images.githubusercontent.com/47554726/87385814-96f9a000-c5d1-11ea-86ca-e321d56d2251.png)
what should i do to fix these bug. thanks

**Comment by Hoshikara** [comment]
yes, copy those files over from the default skin--I haven't skinned those as they're relatively new features
for the other issue, play in fullscreen if possible (alt+enter)

**Comment by wz18207** [comment]
thanks. I've solve my problems.
